# Specify Refined Architect version
refinedarchitectVersion=1.7.0

# Target platform
minecraftVersion=26.3
neoFormVersion=26.3-1
neoForgeVersion=26.3.0.4-beta
modVersion=3.2.1-mc26.3-port.1
jeiVersion=31.0.0.5
refinedstorageQuartzArsenalVersion=2.0.6

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
